Feat add infra ss58 did resolver
InfraBlockchain/infra-did-resolver pull request #1
Opened 2023-02-23 06:34 UTC by keispace

add infra ss58 did resolver (test & readme 작성)
- 테스트를 위해 노드에 did가 등록되어 있어야 해서 로컬 테스트용 코드(readyTest, endTest) 포함됬습니다.

2023-02-24 01:13 UTC, sweatpotato13 requested changes
👍

2023-02-24 01:13 UTC, sweatpotato13 commented on src/infra-ss58-did-resolver.ts
> +                    publicKeyBase58: b58.encode(decodeAddress(ss58ID))
현재 InfraBlockchain 기반 DID Document에서 `publicKeyHex` 로 public key를 제공하고 있어서 동일한 포맷으로 맞추면 좋을 것 같습니다.

2023-02-24 01:47 UTC, sweatpotato13 approved these changes
👍

2023-03-07 07:50 UTC, keispace commented
did-js에서 작업 완료후 재 PR

2023-03-07 07:50 UTC, closed without merging